import { motion } from 'motion/react';
import { useInView } from './hooks/useInView';

export function EcoRangeDetail() {
  const { ref, isInView } = useInView();

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 relative">
      <div className="max-w-6xl mx-auto" ref={ref}>
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl sm:text-5xl font-bold leading-[1.2] mb-4 bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
            EcoRange
          </h2>
          <div className="w-20 h-1 bg-gradient-to-r from-purple-500 to-pink-500 mx-auto mb-4" />
          <p className="text-lg text-gray-400 max-w-3xl mx-auto">
            Agricultural brand UI concept created with Figma AI for cucumber retail and bulk buyers.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative group"
        >
          <div className="absolute inset-0 bg-gradient-to-br from-purple-500/20 to-blue-500/20 rounded-3xl blur-2xl opacity-60 group-hover:opacity-100 transition-opacity duration-300" />

          <div className="relative bg-[#0a0118]/85 backdrop-blur-xl border border-purple-500/20 rounded-3xl p-6 sm:p-10 hover:border-purple-500/40 transition-all duration-300">
            <div className="space-y-8">
              {/* Overview */}
              <div className="rounded-2xl border border-purple-500/20 bg-gradient-to-br from-purple-500/10 to-pink-500/10 p-6">
                <h3 className="text-2xl font-semibold text-white">Overview</h3>
                <p className="text-gray-300 mt-2 leading-relaxed text-[15px] sm:text-base">
                  Conceptualized and designed a website UI for Ecorenge, an agricultural brand selling cucumbers to
                  both individual customers and bulk buyers. The interface was created through detailed prompt-driven
                  design using Figma AI, guided by defined product goals and user needs.
                </p>
              </div>

              {/* Process */}
              <div className="rounded-2xl border border-purple-500/20 bg-[#0a0118]/60 p-6">
                <h4 className="text-lg font-semibold text-white mb-2">Process</h4>
                <ul className="mt-3 grid gap-2 text-gray-300 text-[15px] sm:text-base list-disc list-inside marker:text-purple-300">
                  <li>Defined the brand concept, target audience, and value proposition</li>
                  <li>Specified purchase flows for retail and bulk ordering</li>
                  <li>Wrote structured prompts covering layout, content hierarchy, CTAs, and tone</li>
                  <li>Reviewed and selected AI-generated UI that best met product and UX goals</li>
                </ul>
              </div>

              {/* Key Focus Areas */}
              <div className="rounded-2xl border border-purple-500/20 bg-[#0a0118]/60 p-6">
                <h4 className="text-lg font-semibold text-white mb-2">Key Focus Areas</h4>
                <ul className="mt-3 grid gap-2 text-gray-300 text-[15px] sm:text-base list-disc list-inside marker:text-purple-300">
                  <li>Clear differentiation between Buy Now and Bulk Order flows</li>
                  <li>Trust-building visuals suitable for an agricultural brand</li>
                  <li>Simple, conversion-focused layout</li>
                </ul>
              </div>

              {/* AI Disclosure */}
              <div className="rounded-2xl border border-purple-500/20 bg-gradient-to-br from-purple-500/10 to-blue-500/10 p-6">
                <h4 className="text-lg font-semibold text-white mb-2">AI Disclosure</h4>
                <p className="text-gray-300 text-[15px] sm:text-base">
                  The final UI was generated by Figma AI based on prompts and product direction I provided.
                </p>
              </div>

              {/* Wireframe + Screens */}
              <div className="rounded-2xl border border-purple-500/20 bg-[#0a0118]/60 p-6">
                <div className="mb-4">
                  <a
                    href="https://www.figma.com/make/fNH2qzkKeJEasouBXt7iQN/Agriculture-Website?p=f&t=kGQvhbW2BSJZKgcQ-0"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 text-blue-300 hover:text-blue-200 font-semibold"
                    style={{
                      textDecoration: 'underline',
                      textDecorationThickness: '2px',
                      textUnderlineOffset: '4px',
                    }}
                  >
                    View Figma Design
                  </a>
                </div>

                <h4 className="text-lg font-semibold text-white mb-2">Wireframe</h4>

                <div className="overflow-hidden rounded-xl border border-purple-500/20">
                  <img
                    src="images/eco.wireframe.png"
                    alt="EcoRange wireframe"
                    className="w-full h-auto block"
                  />
                </div>

                {/* 🔥 Increased gap HERE */}
                <div className="h-20 sm:h-28" />
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {[
                    'images/eco.header.png',
                    'images/eco.about.png',
                    'images/eco.product.png',
                    'images/eco.why.png',
                    'images/eco.contact.png',
                    'images/eco.footer.png',
                  ].map((src) => (
                    <div
                      key={src}
                      className="overflow-hidden rounded-xl border border-purple-500/20 bg-[#0a0118]/70"
                    >
                      <img
                        src={src}
                        alt="EcoRange section"
                        className="w-full h-auto block"
                      />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

